INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (1, '1', 3);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (2, '2', 1);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (3, '3', 2);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (4, '4', 1);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (5, '5', 1);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (6, '6', 2);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (7, '7', 2);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (8, '8', 2);
INSERT INTO hotel_app.room (id, room_no, room_type_id) VALUES (9, '9', 3);